version: 0.0
os: linux
files:
  - source: /
    destination: /opt/www/application.com/codedeploy
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/codedeploy/setup_current_release.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/codedeploy/clean_old_releases.sh
      timeout: 60
      runas: ec2-user
