version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mv node_modules /tmp/
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > ./REVISION
artifacts:
  files:
    - '**/*'
